@hostname=localhost
@port=5177
GET https://{{hostname}}:{{port}}/Start/Index
###
GET https://{{hostname}}:{{port}}/Start/One
###
GET https://{{hostname}}:{{port}}/Start/Two
###
GET https://{{hostname}}:{{port}}/Start/Three
###
POST http://{{hostname}}:{{port}}/Start/Index 
###
POST http://{{hostname}}:{{port}}/Start/One
###
POST http://{{hostname}}:{{port}}/Start/Two
###
POST http://{{hostname}}:{{port}}/Start/Three
###
GET https://www.belstu.by