--USERS
INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('IVAN', 'IVANOV', 'IVAN.IVANOV@mail.ru');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('kirill', 'makrush', 'kirill.makrush@mail.ru');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('ilya', 'semkin', 'ilya.semkin@mail.ru');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('John', 'Doe', 'john.doe@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Jane', 'Smith', 'jane.smith@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Michael', 'Johnson', 'michael.johnson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Emily', 'Williams', 'emily.williams@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('David', 'Brown', 'david.brown@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Olivia', 'Taylor', 'olivia.taylor@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Daniel', 'Anderson', 'daniel.anderson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Sophia', 'Thomas', 'sophia.thomas@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Matthew', 'Martinez', 'matthew.martinez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Isabella', 'Hernandez', 'isabella.hernandez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('William', 'Lopez', 'william.lopez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Ava', 'Gonzalez', 'ava.gonzalez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('James', 'Wilson', 'james.wilson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Mia', 'Anderson', 'mia.anderson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Benjamin', 'Moore', 'benjamin.moore@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Charlotte', 'Lee', 'charlotte.lee@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Alexander', 'Clark', 'alexander.clark@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Ella', 'Lewis', 'ella.lewis@example.com');   
    
INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Liam', 'Smith', 'liam.smith@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Emma', 'Johnson', 'emma.johnson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Noah', 'Williams', 'noah.williams@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Olivia', 'Brown', 'olivia.brown@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Sophia', 'Taylor', 'sophia.taylor@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Jackson', 'Anderson', 'jackson.anderson@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Aiden', 'Thomas', 'aiden.thomas@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Lucas', 'Martinez', 'lucas.martinez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Avery', 'Hernandez', 'avery.hernandez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Ethan', 'Lopez', 'ethan.lopez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Harper', 'Gonzalez', 'harper.gonzalez@example.com');

INSERT INTO USERS (USER_NAME, USER_SURNAME, USER_EMAIL)
    VALUES ('Madison', 'Wilson', 'madison.wilson@example.com'); 

--PRICES


INSERT INTO PRICE (PRICE_MONTH, PRICE_QUARTER, PRICE_SIX_MONTH, PRICE_YEAR)
	VALUES (15, 40, 70, 120);

INSERT INTO PRICE (PRICE_MONTH, PRICE_QUARTER, PRICE_SIX_MONTH, PRICE_YEAR)
	VALUES (20, 55, 90, 160);

INSERT INTO PRICE (PRICE_MONTH, PRICE_QUARTER, PRICE_SIX_MONTH, PRICE_YEAR)
	VALUES (0, 0, 0, 0);

INSERT INTO PRICE (PRICE_MONTH, PRICE_QUARTER, PRICE_SIX_MONTH, PRICE_YEAR)
	VALUES (10, 25, 45, 80); 
    
    SELECT *FROM PRICE;
    
--SOFTWARE_TYPE

INSERT INTO SOFTWARE_TYPE(SOFTWARE_TYPE,SOFTWARE_TYPE_INFO,PRICE_ID)
	VALUES ('Office Suite', 'Comprehensive productivity software', 21);

INSERT INTO SOFTWARE_TYPE (SOFTWARE_TYPE,SOFTWARE_TYPE_INFO,PRICE_ID)
	VALUES ('Image Editing', 'Professional image editing software', 22);

INSERT INTO SOFTWARE_TYPE (SOFTWARE_TYPE,SOFTWARE_TYPE_INFO,PRICE_ID)
	VALUES ('Web Browser', 'Internet browsing application', 23);

INSERT INTO SOFTWARE_TYPE(SOFTWARE_TYPE,SOFTWARE_TYPE_INFO,PRICE_ID)
	VALUES ('Database Management System', 'Relational database management system', 24);

INSERT INTO SOFTWARE_TYPE(SOFTWARE_TYPE,SOFTWARE_TYPE_INFO,PRICE_ID)
	VALUES ('IDE', 'Integrated Development Environment', 23);
    
--SOFTWARE

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Microsoft Office', '2021', 'Microsoft Corporation',26);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Microsoft Word', '2021', 'Microsoft Corporation',26);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Visual Studio Code', '1.55.2', 'Microsoft Corporation',30);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Visual Studio', '1.21.2', 'Microsoft Corporation',30);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Adobe Photoshop', 'CC 2022', 'Adobe Inc.',27);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Adobe Illustrator', 'CC 2022', 'Adobe Inc.',27);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Google Chrome', '89.0.4389.82', 'Google LLC',28);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('MySQL Server', '8.0.23', 'Oracle Corporation',29);

INSERT INTO SOFTWARE (SOFTWARE_NAME,SOFTWARE_VERSION,SOFTWARE_COMPANY_DEVELOPER,SOFTWARE_TYPE_ID)
	VALUES ('Oracle Database', '19c', 'Oracle Corporation',29);
    
--LICENSES
    
INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(21,41,TO_DATE('2021-06-11','YYYY-MM-DD'),TO_DATE('2021-07-11','YYYY-MM-DD'),'COMPUTER');
    
INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(21,41,TO_DATE('2021-07-12','YYYY-MM-DD'),TO_DATE('2021-08-12','YYYY-MM-DD'),'COMPUTER');

INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(22,42,TO_DATE('2021-06-11','YYYY-MM-DD'),TO_DATE('2021-07-11','YYYY-MM-DD'),'TELEPHONE');
    
INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(23,42,TO_DATE('2021-07-12','YYYY-MM-DD'),TO_DATE('2021-08-12','YYYY-MM-DD'),'COMPUTER');
    
DELETE LICENSES WHERE LICENSE_ID = 25 OR LICENSE_ID = 26 OR LICENSE_ID = 27 OR LICENSE_ID = 28;
    
SELECT *FROM LICENSES;
    
--3
    SELECT SOFTWARE_TYPE, SUM(PRICE_MONTH) AS TOTAL_MONTHLY_PRICE, SUM(PRICE_QUARTER) AS TOTAL_QUARTERLY_PRICE, SUM(PRICE_SIX_MONTH) AS TOTAL_SIX_MONTH_PRICE, SUM(PRICE_YEAR) AS TOTAL_YEARLY_PRICE 
		FROM SOFTWARE 
			INNER JOIN SOFTWARE_TYPE
				ON SOFTWARE.SOFTWARE_TYPE_ID = SOFTWARE_TYPE.SOFTWARE_TYPE_ID
					INNER JOIN PRICE 
						ON SOFTWARE_TYPE.PRICE_ID = PRICE.PRICE_ID
							GROUP BY (SOFTWARE_TYPE);
                            
--4
    SELECT
		t.SOFTWARE_ID,
		t.NUMBER_OF_LICENSE,
		t.PRICE_MONTH,
		t.PRICE_QUARTER,
		t.PRICE_SIX_MONTH,
		t.PRICE_YEAR,
		t.PERCENTAGE_OF_LICENSE,
		t.TOTAL_ALL_LICENSES,
		t.TOTAL_ALL_LICENSE_COST,
		(t.TOTAL_LICENSE_COST * 100.0 / t.TOTAL_ALL_LICENSE_COST) AS PERCENTAGE_OF_COST
	FROM (
		SELECT
			l.SOFTWARE_ID,
			COUNT(l.SOFTWARE_ID) AS NUMBER_OF_LICENSE,
			SUM(p.PRICE_MONTH) AS PRICE_MONTH,
			SUM(p.PRICE_QUARTER) AS PRICE_QUARTER,
			SUM(p.PRICE_SIX_MONTH) AS PRICE_SIX_MONTH,
			SUM(p.PRICE_YEAR) AS PRICE_YEAR,
			(COUNT(l.SOFTWARE_ID) * 100.0 / (SELECT COUNT(LICENSE_ID) FROM LICENSES)) AS PERCENTAGE_OF_LICENSE,
			(SELECT COUNT(LICENSE_ID) FROM LICENSES) AS TOTAL_ALL_LICENSES,
			(SELECT SUM(p.PRICE_MONTH + p.PRICE_QUARTER + p.PRICE_SIX_MONTH + p.PRICE_YEAR) FROM LICENSES
			 JOIN SOFTWARE ON LICENSES.SOFTWARE_ID = SOFTWARE.SOFTWARE_ID
			 JOIN SOFTWARE_TYPE ON SOFTWARE.SOFTWARE_TYPE_ID = SOFTWARE_TYPE.SOFTWARE_TYPE_ID
			 JOIN PRICE p ON SOFTWARE_TYPE.PRICE_ID = p.PRICE_ID) AS TOTAL_ALL_LICENSE_COST,
			SUM(p.PRICE_MONTH + p.PRICE_QUARTER + p.PRICE_SIX_MONTH + p.PRICE_YEAR) AS TOTAL_LICENSE_COST
		FROM
			LICENSES l
			INNER JOIN SOFTWARE s ON l.SOFTWARE_ID = s.SOFTWARE_ID
			INNER JOIN SOFTWARE_TYPE st ON s.SOFTWARE_TYPE_ID = st.SOFTWARE_TYPE_ID
			INNER JOIN PRICE p ON st.PRICE_ID = p.PRICE_ID
		GROUP BY
			l.SOFTWARE_ID
	) t;
--5
    SELECT
        S.SOFTWARE_COMPANY_DEVELOPER AS Vendor,
        TRUNC(TO_DATE(L.DATE_OF_PURCHASE, 'DD.MM.YYYY'), 'MONTH') AS Month,
        SUM(P.PRICE_SIX_MONTH) AS TotalExpense
    FROM
        LICENSES L
        INNER JOIN SOFTWARE S ON L.SOFTWARE_ID = S.SOFTWARE_ID
        INNER JOIN SOFTWARE_TYPE ST ON S.SOFTWARE_TYPE_ID = ST.SOFTWARE_TYPE_ID
        INNER JOIN PRICE P ON ST.PRICE_ID = P.PRICE_ID
    WHERE
        L.DATE_OF_PURCHASE >= TRUNC(ADD_MONTHS(CURRENT_TIMESTAMP, -6), 'MONTH')
    GROUP BY
        S.SOFTWARE_COMPANY_DEVELOPER,
        TRUNC(TO_DATE(L.DATE_OF_PURCHASE, 'DD.MM.YYYY'), 'MONTH')
    ORDER BY
        S.SOFTWARE_COMPANY_DEVELOPER,
        Month;
--6
    SELECT L.LICENSE_TYPE AS DEVICE_TYPE, ST.SOFTWARE_TYPE, S.SOFTWARE_NAME, COUNT(*) AS UsageCount
		FROM LICENSES L
		INNER JOIN SOFTWARE S ON L.SOFTWARE_ID = S.SOFTWARE_ID
		INNER JOIN SOFTWARE_TYPE ST ON S.SOFTWARE_TYPE_ID = ST.SOFTWARE_TYPE_ID
			GROUP BY L.LICENSE_TYPE, ST.SOFTWARE_TYPE, S.SOFTWARE_NAME
				ORDER BY UsageCount DESC;


INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(28,50,TO_DATE('2023-10-12','YYYY-MM-DD'),TO_DATE('2023-11-12','YYYY-MM-DD'),'COMPUTER');
INSERT INTO LICENSES (SOFTWARE_ID,USER_ID,DATE_OF_PURCHASE,EXPIRATION_DATE,LICENSE_TYPE)
    VALUES(29,50,TO_DATE('2023-10-12','YYYY-MM-DD'),TO_DATE('2023-11-12','YYYY-MM-DD'),'LAPTOP');



select *from licenses;
DELETE FROM LICENSES WHERE LICENSE_ID = 21 OR LICENSE_ID = 22 OR LICENSE_ID = 23 OR LICENSE_ID = 24;

SELECT *FROM SOFTWARE;
SELECT *FROM USERS;

SELECT * FROM SOFTWARE 
			INNER JOIN SOFTWARE_TYPE
				ON SOFTWARE.SOFTWARE_TYPE_ID = SOFTWARE_TYPE.SOFTWARE_TYPE_ID
                INNER JOIN PRICE 
						ON SOFTWARE_TYPE.PRICE_ID = PRICE.PRICE_ID
    