--CREATION OF A DB FOR SOFTWARE LICENSES MANAGEMENT

	CREATE TABLE USERS(
		USER_ID INT IDENTITY(1,1) PRIMARY KEY,
		USER_NAME NVARCHAR(20) NOT NULL,
		USER_SURNAME NVARCHAR(20) NOT NULL,
		USER_EMAIL NVARCHAR(120) NOT NULL UNIQUE,
	);
	DROP TABLE USERS;

	CREATE TABLE SOFTWARE(
		SOFTWARE_ID INT IDENTITY(1,1) PRIMARY KEY,
		SOFTWARE_NAME NVARCHAR(120) NOT NULL,
		SOFTWARE_VERSION NVARCHAR(140) NOT NULL,
		SOFTWARE_COMPANY_DEVELOPER NVARCHAR(120) NOT NULL,
		SOFTWARE_TYPE_ID INT FOREIGN KEY REFERENCES SOFTWARE_TYPE(SOFTWARE_TYPE_ID)
	)
	DROP TABLE SOFTWARE;

	CREATE TABLE SOFTWARE_TYPE(
		SOFTWARE_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY,
		SOFTWARE_TYPE NVARCHAR(120),
		SOFTWARE_TYPE_INFO NVARCHAR(320),
		PRICE_ID INT FOREIGN KEY REFERENCES PRICE(PRICE_ID)
	)
	DROP TABLE SOFTWARE_TYPE;

	CREATE TABLE PRICE(
		PRICE_ID INT IDENTITY(1,1) PRIMARY KEY,
		PRICE_MONTH INT NOT NULL,
		PRICE_QUARTER INT NOT NULL,
		PRICE_SIX_MONTH INT NOT NULL,
		PRICE_YEAR INT NOT NULL,
	)
	DROP TABLE PRICE;

	CREATE TABLE LICENSES(
		LICENSE_ID INT IDENTITY(1,1) PRIMARY KEY,
		SOFTWARE_ID INT FOREIGN KEY REFERENCES SOFTWARE(SOFTWARE_ID),
		USER_NAME INT FOREIGN KEY REFERENCES USERS(USER_ID),
		DATE_OF_PURCHASE NVARCHAR(40) NOT NULL,
		EXPIRATION_DATE NVARCHAR(40) NOT NULL,
	)
	DROP TABLE LICENSES;

	ALTER TABLE LICENSES ADD LICENSE_TYPE VARCHAR(50);

